-- Run ONCE as a privileged user (SYS/SYSTEM) connected to the PLUGGABLE database (PDB), not CDB$ROOT.
-- Passwords are prompted and never stored in the repository.
WHENEVER SQLERROR EXIT SQL.SQLCODE
ACCEPT owner_pwd CHAR PROMPT 'Password for EIMS_OWNER (schema owner): ' HIDE
ACCEPT app_pwd   CHAR PROMPT 'Password for EIMS_APP (application account): ' HIDE
CREATE USER EIMS_OWNER IDENTIFIED BY "&owner_pwd" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE VIEW, CREATE PROCEDURE TO EIMS_OWNER;
CREATE USER EIMS_APP IDENTIFIED BY "&app_pwd";
GRANT CREATE SESSION TO EIMS_APP;
PROMPT Users created.
