-- DEV ONLY. Run as EIMS_OWNER. Drops ALL EIMS tables (V001-V004). ORA-00942 errors are harmless.
DROP TABLE EIMS_KNOWLEDGE_ASSET CASCADE CONSTRAINTS PURGE;
DROP TABLE EIMS_BENEFIT CASCADE CONSTRAINTS PURGE;
DROP TABLE EIMS_EXECUTION CASCADE CONSTRAINTS PURGE;
DROP TABLE EIMS_EXECUTION_RECOMMENDATION CASCADE CONSTRAINTS PURGE;
DROP TABLE EIMS_PORTFOLIO_MEMBERSHIP CASCADE CONSTRAINTS PURGE;
DROP TABLE EIMS_PORTFOLIO_CANDIDATE CASCADE CONSTRAINTS PURGE;
DROP TABLE EIMS_G04_COMMITTEE_VOTE CASCADE CONSTRAINTS PURGE;
DROP TABLE EIMS_G04_GOVERNANCE_SNAPSHOT CASCADE CONSTRAINTS PURGE;
DROP TABLE EIMS_G04_ASSESSMENT CASCADE CONSTRAINTS PURGE;
DROP TABLE EIMS_EVALUATION_SNAPSHOT CASCADE CONSTRAINTS PURGE;
DROP TABLE EIMS_EVALUATION_ASSIGNMENT CASCADE CONSTRAINTS PURGE;
DROP TABLE EIMS_EVALUATION_PLAN CASCADE CONSTRAINTS PURGE;
DROP TABLE EIMS_IDEMPOTENCY CASCADE CONSTRAINTS PURGE;
DROP TABLE EIMS_OUTBOX CASCADE CONSTRAINTS PURGE;
DROP TABLE EIMS_DOMAIN_DECISION CASCADE CONSTRAINTS PURGE;
DROP TABLE EIMS_AUDIT_LOG CASCADE CONSTRAINTS PURGE;
DROP TABLE EIMS_AGGREGATE CASCADE CONSTRAINTS PURGE;
