-- Self-test for V001. Run as EIMS_OWNER. Writes test rows then ROLLBACKs. Expect every line to start with PASS.
SET SERVEROUTPUT ON
DECLARE
  v_cnt NUMBER;
  PROCEDURE rep(p_name VARCHAR2, p_ok BOOLEAN) IS
  BEGIN DBMS_OUTPUT.PUT_LINE(CASE WHEN p_ok THEN 'PASS ' ELSE 'FAIL ' END || p_name); END;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM USER_TABLES
   WHERE TABLE_NAME IN ('EIMS_AGGREGATE','EIMS_AUDIT_LOG','EIMS_DOMAIN_DECISION','EIMS_OUTBOX','EIMS_IDEMPOTENCY');
  rep('5 core tables exist', v_cnt = 5);

  INSERT INTO EIMS_AGGREGATE (AGGREGATE_ID, AGGREGATE_TYPE, AGG_STATE, ENTITY_VERSION) VALUES ('T-1','IDEA','DRAFT',1);
  UPDATE EIMS_AGGREGATE SET AGG_STATE='SUBMITTED', ENTITY_VERSION=2 WHERE AGGREGATE_ID='T-1' AND ENTITY_VERSION=1;
  rep('optimistic update with correct version changes 1 row', SQL%ROWCOUNT = 1);
  UPDATE EIMS_AGGREGATE SET AGG_STATE='X', ENTITY_VERSION=2 WHERE AGGREGATE_ID='T-1' AND ENTITY_VERSION=1;
  rep('stale version changes 0 rows (conflict detected)', SQL%ROWCOUNT = 0);

  INSERT INTO EIMS_AUDIT_LOG (AUDIT_ID, PERSON_ID, NETWORK_IDENTITY, IDENTITY_SOURCE, ROLES_JSON, AGGREGATE_ID,
                              ENTITY_VERSION, OCCURRED_AT, CORRELATION_ID, COMMAND_NAME)
  VALUES ('A-1','P1','DOMAIN\u1','WINDOWS_PRINCIPAL','["IDEA_OWNER"]','T-1',2,SYSTIMESTAMP,'C-1','ideas.submit-g04');
  BEGIN UPDATE EIMS_AUDIT_LOG SET PERSON_ID='X' WHERE AUDIT_ID='A-1'; rep('audit UPDATE is blocked', FALSE);
  EXCEPTION WHEN OTHERS THEN rep('audit UPDATE is blocked', SQLCODE = -20001); END;
  BEGIN DELETE FROM EIMS_AUDIT_LOG WHERE AUDIT_ID='A-1'; rep('audit DELETE is blocked', FALSE);
  EXCEPTION WHEN OTHERS THEN rep('audit DELETE is blocked', SQLCODE = -20001); END;

  INSERT INTO EIMS_IDEMPOTENCY (COMMAND_NAME, AGGREGATE_ID, IDEMPOTENCY_KEY, FINGERPRINT, RESULT_JSON) VALUES ('c','T-1','k1','f','{}');
  BEGIN INSERT INTO EIMS_IDEMPOTENCY (COMMAND_NAME, AGGREGATE_ID, IDEMPOTENCY_KEY, FINGERPRINT, RESULT_JSON) VALUES ('c','T-1','k1','f','{}');
        rep('duplicate idempotency key rejected', FALSE);
  EXCEPTION WHEN DUP_VAL_ON_INDEX THEN rep('duplicate idempotency key rejected', TRUE); END;

  BEGIN INSERT INTO EIMS_OUTBOX (MESSAGE_ID, EVENT_NAME, AGGREGATE_ID, AGGREGATE_VERSION, CORRELATION_ID, OCCURRED_AT, PAYLOAD_JSON)
        VALUES ('M-1','E','T-1',2,'C-1',SYSTIMESTAMP,'not json'); rep('invalid JSON payload rejected', FALSE);
  EXCEPTION WHEN OTHERS THEN rep('invalid JSON payload rejected', SQLCODE = -2290); END;

  ROLLBACK;
  DBMS_OUTPUT.PUT_LINE('Test rows rolled back.');
END;
/
