-- Verifies the ACR-S1b conventions against the data dictionary. Run as EIMS_OWNER.
SET SERVEROUTPUT ON
DECLARE
  v NUMBER;
  PROCEDURE rep(p_name VARCHAR2, p_ok BOOLEAN) IS
  BEGIN DBMS_OUTPUT.PUT_LINE(CASE WHEN p_ok THEN 'PASS ' ELSE 'FAIL ' END || p_name); END;
BEGIN
  SELECT COUNT(*) INTO v FROM USER_TABLES WHERE TABLE_NAME IN ('EIMS_AGGREGATE','EIMS_AUDIT_LOG','EIMS_DOMAIN_DECISION','EIMS_OUTBOX','EIMS_IDEMPOTENCY','EIMS_EVALUATION_PLAN','EIMS_EVALUATION_ASSIGNMENT','EIMS_EVALUATION_SNAPSHOT','EIMS_G04_ASSESSMENT','EIMS_G04_GOVERNANCE_SNAPSHOT','EIMS_G04_COMMITTEE_VOTE','EIMS_PORTFOLIO_CANDIDATE','EIMS_PORTFOLIO_MEMBERSHIP','EIMS_EXECUTION_RECOMMENDATION','EIMS_EXECUTION','EIMS_BENEFIT','EIMS_KNOWLEDGE_ASSET');
  rep('all 17 tables exist', v = 17);
  SELECT COUNT(*) INTO v FROM USER_TAB_COLUMNS WHERE COLUMN_NAME = 'VERSION';
  rep('no column named VERSION (ENTITY_VERSION is the standard)', v = 0);
  SELECT COUNT(*) INTO v FROM USER_TAB_COLUMNS WHERE DATA_TYPE LIKE 'TIMESTAMP%' AND DATA_TYPE NOT LIKE '%WITH TIME ZONE';
  rep('every timestamp column has a time zone', v = 0);
  SELECT COUNT(*) INTO v FROM USER_TAB_COLUMNS WHERE DATA_TYPE = 'VARCHAR2' AND CHAR_USED <> 'C';
  rep('every VARCHAR2 uses CHAR semantics', v = 0);
  SELECT COUNT(*) INTO v FROM USER_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'P' AND CONSTRAINT_NAME LIKE 'SYS\_C%' ESCAPE '\';
  rep('every primary key is named', v = 0);
  SELECT COUNT(*) INTO v FROM USER_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'R' AND TABLE_NAME IN ('EIMS_AUDIT_LOG','EIMS_OUTBOX','EIMS_DOMAIN_DECISION') AND R_CONSTRAINT_NAME IN (SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'EIMS_AGGREGATE');
  rep('audit/outbox/decision have no FK to EIMS_AGGREGATE (soft reference)', v = 0);
  SELECT COUNT(*) INTO v FROM USER_TRIGGERS WHERE STATUS = 'ENABLED' AND TABLE_NAME LIKE 'EIMS%';
  rep('4 append-only triggers enabled', v = 4);
END;
/
