-- EIMS S1 v1.1 / ACR-S1 + ACR-S1b (audit/outbox/decision reference aggregates softly: no FK) : core persistence (state, audit, outbox, idempotency, decision history)
-- Target: Oracle 12.2+ / 19c / 21c. Run as EIMS_OWNER. Times are stored with time zone (UTC from app).
-- Oracle note: '' (empty string) is NULL. The application must never rely on empty strings.

CREATE TABLE EIMS_AGGREGATE (
  AGGREGATE_ID           VARCHAR2(128 CHAR) NOT NULL,
  AGGREGATE_TYPE         VARCHAR2(64 CHAR)  NOT NULL,
  AGG_STATE              VARCHAR2(64 CHAR)  NOT NULL,
  ENTITY_VERSION         NUMBER(19)         NOT NULL,   -- optimistic concurrency token
  OWNER_PERSON_ID        VARCHAR2(64 CHAR),
  OWNER_ROLE             VARCHAR2(64 CHAR),
  SCOPE_CODE             VARCHAR2(128 CHAR),
  WORK_ROUTING_ROLE      VARCHAR2(64 CHAR),
  STATE_MUTATION_VERSION NUMBER(19),
  RULE_FACTS_JSON        CLOB,
  CREATED_AT             TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT             TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_EIMS_AGGREGATE PRIMARY KEY (AGGREGATE_ID),
  CONSTRAINT CK_EIMS_AGG_VERSION CHECK (ENTITY_VERSION >= 0),
  CONSTRAINT CK_EIMS_AGG_FACTS CHECK (RULE_FACTS_JSON IS JSON)
);
CREATE INDEX IX_EIMS_AGG_TYPE_STATE ON EIMS_AGGREGATE (AGGREGATE_TYPE, AGG_STATE);
CREATE INDEX IX_EIMS_AGG_ROUTING    ON EIMS_AGGREGATE (WORK_ROUTING_ROLE, AGG_STATE);

CREATE TABLE EIMS_AUDIT_LOG (
  AUDIT_SEQ        NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  AUDIT_ID         VARCHAR2(128 CHAR) NOT NULL,
  PERSON_ID        VARCHAR2(64 CHAR)  NOT NULL,
  NETWORK_IDENTITY VARCHAR2(256 CHAR) NOT NULL,
  IDENTITY_SOURCE  VARCHAR2(64 CHAR)  NOT NULL,
  ROLES_JSON       CLOB NOT NULL,
  ASSIGNMENT_ID    VARCHAR2(128 CHAR),
  AGGREGATE_ID     VARCHAR2(128 CHAR) NOT NULL,
  AGGREGATE_TYPE  VARCHAR2(64 CHAR),      -- soft reference, see ACR-S1b D2
  ENTITY_VERSION   NUMBER(19)         NOT NULL,
  RULE_SET         VARCHAR2(128 CHAR),
  OCCURRED_AT      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  CORRELATION_ID   VARCHAR2(128 CHAR) NOT NULL,
  COMMAND_NAME     VARCHAR2(128 CHAR) NOT NULL,
  CONSTRAINT PK_EIMS_AUDIT_LOG PRIMARY KEY (AUDIT_SEQ),
  CONSTRAINT UQ_EIMS_AUDIT_ID UNIQUE (AUDIT_ID),
  CONSTRAINT CK_EIMS_AUDIT_ROLES CHECK (ROLES_JSON IS JSON)
);
CREATE INDEX IX_EIMS_AUDIT_AGG  ON EIMS_AUDIT_LOG (AGGREGATE_ID, ENTITY_VERSION);
CREATE INDEX IX_EIMS_AUDIT_CORR ON EIMS_AUDIT_LOG (CORRELATION_ID);

CREATE TABLE EIMS_DOMAIN_DECISION (
  DECISION_ID    VARCHAR2(128 CHAR) NOT NULL,
  DECISION_TYPE  VARCHAR2(64 CHAR)  NOT NULL,
  OUTCOME        VARCHAR2(64 CHAR)  NOT NULL,
  AGGREGATE_ID   VARCHAR2(128 CHAR) NOT NULL,
  AGGREGATE_TYPE  VARCHAR2(64 CHAR),      -- soft reference, see ACR-S1b D2
  ENTITY_VERSION NUMBER(19)         NOT NULL,
  PERSON_ID      VARCHAR2(64 CHAR)  NOT NULL,
  ASSIGNMENT_ID  VARCHAR2(128 CHAR) NOT NULL,
  DECIDED_AT     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  CORRELATION_ID VARCHAR2(128 CHAR) NOT NULL,
  NOTE           VARCHAR2(4000 CHAR),
  FACTS_JSON     CLOB,
  CONSTRAINT PK_EIMS_DECISION PRIMARY KEY (DECISION_ID),
  CONSTRAINT CK_EIMS_DECISION_FACTS CHECK (FACTS_JSON IS JSON)
);
CREATE INDEX IX_EIMS_DECISION_AGG ON EIMS_DOMAIN_DECISION (AGGREGATE_ID, ENTITY_VERSION);

CREATE TABLE EIMS_OUTBOX (
  OUTBOX_SEQ        NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  MESSAGE_ID        VARCHAR2(128 CHAR) NOT NULL,
  EVENT_NAME        VARCHAR2(128 CHAR) NOT NULL,
  AGGREGATE_ID      VARCHAR2(128 CHAR) NOT NULL,
  AGGREGATE_TYPE  VARCHAR2(64 CHAR),      -- soft reference, see ACR-S1b D2
  AGGREGATE_VERSION NUMBER(19)         NOT NULL,
  CORRELATION_ID    VARCHAR2(128 CHAR) NOT NULL,
  OCCURRED_AT       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  PAYLOAD_JSON      CLOB,
  DISPATCH_STATUS   VARCHAR2(16 CHAR) DEFAULT 'PENDING' NOT NULL,
  ATTEMPTS          NUMBER(10)        DEFAULT 0 NOT NULL,
  NEXT_ATTEMPT_AT   TIMESTAMP(6) WITH TIME ZONE,
  SENT_AT           TIMESTAMP(6) WITH TIME ZONE,
  LAST_ERROR        VARCHAR2(1000 CHAR),
  CONSTRAINT PK_EIMS_OUTBOX PRIMARY KEY (OUTBOX_SEQ),
  CONSTRAINT UQ_EIMS_OUTBOX_MSG UNIQUE (MESSAGE_ID),
  CONSTRAINT CK_EIMS_OUTBOX_STATUS CHECK (DISPATCH_STATUS IN ('PENDING','SENT','FAILED')),
  CONSTRAINT CK_EIMS_OUTBOX_PAYLOAD CHECK (PAYLOAD_JSON IS JSON)
);
CREATE INDEX IX_EIMS_OUTBOX_DISPATCH ON EIMS_OUTBOX (DISPATCH_STATUS, OUTBOX_SEQ);

CREATE TABLE EIMS_IDEMPOTENCY (
  COMMAND_NAME    VARCHAR2(128 CHAR) NOT NULL,
  AGGREGATE_ID    VARCHAR2(128 CHAR) NOT NULL,
  IDEMPOTENCY_KEY VARCHAR2(200 CHAR) NOT NULL,
  FINGERPRINT     VARCHAR2(128 CHAR) NOT NULL,
  RESULT_JSON     CLOB NOT NULL,
  CREATED_AT      TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_EIMS_IDEMPOTENCY PRIMARY KEY (COMMAND_NAME, AGGREGATE_ID, IDEMPOTENCY_KEY),
  CONSTRAINT CK_EIMS_IDEM_RESULT CHECK (RESULT_JSON IS JSON)
);

-- Append-only enforcement (second layer; first layer is that EIMS_APP has no UPDATE/DELETE grant).
CREATE OR REPLACE TRIGGER TRG_EIMS_AUDIT_APPEND_ONLY
BEFORE UPDATE OR DELETE ON EIMS_AUDIT_LOG
BEGIN
  RAISE_APPLICATION_ERROR(-20001, 'EIMS_AUDIT_LOG is append-only');
END;
/
CREATE OR REPLACE TRIGGER TRG_EIMS_DECISION_APPEND_ONLY
BEFORE UPDATE OR DELETE ON EIMS_DOMAIN_DECISION
BEGIN
  RAISE_APPLICATION_ERROR(-20001, 'EIMS_DOMAIN_DECISION is append-only');
END;
/

-- Least privilege for the application account.
GRANT SELECT, INSERT, UPDATE ON EIMS_AGGREGATE       TO EIMS_APP;
GRANT SELECT, INSERT         ON EIMS_AUDIT_LOG       TO EIMS_APP;
GRANT SELECT, INSERT         ON EIMS_DOMAIN_DECISION TO EIMS_APP;
GRANT SELECT, INSERT, UPDATE ON EIMS_OUTBOX          TO EIMS_APP;
GRANT SELECT, INSERT         ON EIMS_IDEMPOTENCY     TO EIMS_APP;
