-- EIMS S1b-2 / V003
-- G04 Assessment + frozen governance/profile snapshots + committee votes
-- Owner schema: EIMS_OWNER
-- Runtime account: EIMS_APP

CREATE TABLE EIMS_G04_ASSESSMENT (
    ID                       VARCHAR2(64 CHAR) NOT NULL,
    IDEA_ID                  VARCHAR2(64 CHAR) NOT NULL,
    IDEA_VERSION             NUMBER(10) NOT NULL,
    EVALUATION_PLAN_ID       VARCHAR2(64 CHAR) NOT NULL,
    STATUS                   VARCHAR2(24 CHAR) NOT NULL,
    PRIORITY                 VARCHAR2(16 CHAR) DEFAULT 'NORMAL' NOT NULL,
    RULE_SET                 VARCHAR2(64 CHAR) NOT NULL,
    ASSIGNED_ROLE            VARCHAR2(64 CHAR) NOT NULL,
    DECISION_ROUTE           VARCHAR2(64 CHAR) NOT NULL,
    DECISION_METHOD          VARCHAR2(64 CHAR) NOT NULL,
    G04_PROFILE_ID           VARCHAR2(64 CHAR),
    STRATEGY_SET_VERSION     VARCHAR2(64 CHAR),
    STRATEGY_SET_ID          VARCHAR2(64 CHAR),
    PRIMARY_OBJECTIVE_CODE   VARCHAR2(128 CHAR),
    CALCULATED_GATE_SCORE    NUMBER(10,2),
    DECISION                  VARCHAR2(24 CHAR),
    DECISION_REASON          VARCHAR2(2000 CHAR),
    DECISION_COMMENT         VARCHAR2(4000 CHAR),
    REVIEW_DATE              TIMESTAMP(6) WITH TIME ZONE,
    DECIDED_AT               TIMESTAMP(6) WITH TIME ZONE,
    DECIDED_BY_ROLE          VARCHAR2(64 CHAR),
    ENTITY_VERSION                  NUMBER(10) DEFAULT 1 NOT NULL,
    THREAD_ID                VARCHAR2(128 CHAR),
    CREATED_AT               TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT               TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_G04_ASSESS_STATUS
      CHECK (STATUS IN ('PENDING','APPROVED','RETURNED','HOLD','REJECTED')),
    CONSTRAINT CK_G04_ASSESS_PRIORITY
      CHECK (PRIORITY IN ('NORMAL','CRITICAL')),
    CONSTRAINT CK_G04_ASSESS_DECISION
      CHECK (DECISION IS NULL OR DECISION IN ('APPROVE','RETURN','HOLD','REJECT')),
    CONSTRAINT CK_G04_ASSESS_VERSION CHECK (ENTITY_VERSION >= 1),
    CONSTRAINT CK_G04_ASSESS_IDEA_VERSION CHECK (IDEA_VERSION >= 1),
    CONSTRAINT UQ_G04_ASSESS_PLAN UNIQUE (EVALUATION_PLAN_ID),
    CONSTRAINT PK_G04_ASSESSMENT PRIMARY KEY (ID)
);

CREATE INDEX IX_G04_ASSESS_IDEA
    ON EIMS_G04_ASSESSMENT (IDEA_ID, IDEA_VERSION);

CREATE INDEX IX_G04_ASSESS_STATUS
    ON EIMS_G04_ASSESSMENT (STATUS, DECISION_ROUTE);

CREATE TABLE EIMS_G04_GOVERNANCE_SNAPSHOT (
    ID                    VARCHAR2(64 CHAR) NOT NULL,
    ASSESSMENT_ID         VARCHAR2(64 CHAR) NOT NULL,
    PROFILE_ID             VARCHAR2(64 CHAR),
    DECISION_ROUTE        VARCHAR2(64 CHAR) NOT NULL,
    VOTE_RULE             VARCHAR2(32 CHAR),
    QUORUM_REQUIRED       NUMBER(10),
    CHAIR_PERSON_ID       VARCHAR2(128 CHAR),
    MEMBER_SNAPSHOT       CLOB,
    PROFILE_SNAPSHOT      CLOB,
    CREATED_AT            TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_G04_GOV_ASSESS
      FOREIGN KEY (ASSESSMENT_ID) REFERENCES EIMS_G04_ASSESSMENT(ID),
    CONSTRAINT CK_G04_GOV_VOTE_RULE
      CHECK (VOTE_RULE IS NULL OR VOTE_RULE IN ('MAJORITY','CONSENSUS','CHAIR_TIEBREAK')),
    CONSTRAINT CK_G04_GOV_QUORUM
      CHECK (QUORUM_REQUIRED IS NULL OR QUORUM_REQUIRED >= 1),
    CONSTRAINT CK_G04_GOV_MEMBER_JSON
      CHECK (MEMBER_SNAPSHOT IS NULL OR MEMBER_SNAPSHOT IS JSON),
    CONSTRAINT CK_G04_GOV_PROFILE_JSON
      CHECK (PROFILE_SNAPSHOT IS NULL OR PROFILE_SNAPSHOT IS JSON),
    CONSTRAINT UQ_G04_GOV_ASSESS UNIQUE (ASSESSMENT_ID),
    CONSTRAINT PK_G04_GOVERNANCE_SNAPSHOT PRIMARY KEY (ID)
);

CREATE OR REPLACE TRIGGER TRG_G04_GOV_IMMUTABLE
BEFORE UPDATE OR DELETE ON EIMS_G04_GOVERNANCE_SNAPSHOT
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(-20041, 'G04 governance snapshot is immutable');
END;
/

CREATE TABLE EIMS_G04_COMMITTEE_VOTE (
    ID                    VARCHAR2(64 CHAR) NOT NULL,
    ASSESSMENT_ID         VARCHAR2(64 CHAR) NOT NULL,
    MEMBER_KEY            VARCHAR2(128 CHAR) NOT NULL,
    VOTE                  VARCHAR2(16 CHAR) NOT NULL,
    NOTE                  VARCHAR2(4000 CHAR) NOT NULL,
    VOTED_AT              TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    ENTITY_VERSION               NUMBER(10) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_G04_VOTE_ASSESS
      FOREIGN KEY (ASSESSMENT_ID) REFERENCES EIMS_G04_ASSESSMENT(ID),
    CONSTRAINT CK_G04_VOTE_VALUE
      CHECK (VOTE IN ('APPROVE','REJECT')),
    CONSTRAINT CK_G04_VOTE_VERSION CHECK (ENTITY_VERSION >= 1),
    CONSTRAINT UQ_G04_VOTE_MEMBER UNIQUE (ASSESSMENT_ID, MEMBER_KEY),
    CONSTRAINT PK_G04_COMMITTEE_VOTE PRIMARY KEY (ID)
);

CREATE INDEX IX_G04_VOTE_ASSESS
    ON EIMS_G04_COMMITTEE_VOTE (ASSESSMENT_ID);

GRANT SELECT, INSERT, UPDATE ON EIMS_G04_ASSESSMENT TO EIMS_APP;
GRANT SELECT, INSERT ON EIMS_G04_GOVERNANCE_SNAPSHOT TO EIMS_APP;
GRANT SELECT, INSERT, UPDATE ON EIMS_G04_COMMITTEE_VOTE TO EIMS_APP;

COMMIT;
