-- EIMS S1b-3 / V004
-- Waves 9-13: Portfolio -> Membership -> Recommendation -> Execution -> Benefit -> Knowledge
-- Owner schema: EIMS_OWNER
-- Runtime account: EIMS_APP

CREATE TABLE EIMS_PORTFOLIO_CANDIDATE (
    ID                       VARCHAR2(64 CHAR) NOT NULL,
    IDEA_ID                  VARCHAR2(64 CHAR) NOT NULL,
    IDEA_VERSION             NUMBER(10) NOT NULL,
    TITLE                    VARCHAR2(1000 CHAR) NOT NULL,
    CANONICAL_TYPE           VARCHAR2(64 CHAR) DEFAULT 'PortfolioIntakeCandidate' NOT NULL,
    ELIGIBILITY_RESULT       VARCHAR2(16 CHAR) NOT NULL,
    ELIGIBILITY_DIMENSIONS   CLOB,
    ELIGIBILITY_RULE_REF     VARCHAR2(128 CHAR),
    ELIGIBILITY_CHECKED_AT   TIMESTAMP(6) WITH TIME ZONE,
    APPROVED_IDEA_VERSION_REF VARCHAR2(128 CHAR) NOT NULL,
    PRIORITY                 VARCHAR2(16 CHAR) DEFAULT 'NORMAL' NOT NULL,
    THREAD_ID                VARCHAR2(128 CHAR),
    ENTITY_VERSION                  NUMBER(10) DEFAULT 1 NOT NULL,
    CREATED_AT               TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT               TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_PORT_IDEA_VERSION CHECK (IDEA_VERSION >= 1),
    CONSTRAINT CK_PORT_ELIGIBILITY CHECK (ELIGIBILITY_RESULT IN ('PASS','FAIL')),
    CONSTRAINT CK_PORT_PRIORITY CHECK (PRIORITY IN ('NORMAL','HIGH','CRITICAL')),
    CONSTRAINT CK_PORT_VERSION CHECK (ENTITY_VERSION >= 1),
    CONSTRAINT CK_PORT_ELIGIBILITY_JSON CHECK (ELIGIBILITY_DIMENSIONS IS NULL OR ELIGIBILITY_DIMENSIONS IS JSON),
    CONSTRAINT UQ_PORT_IDEA_VERSION UNIQUE (IDEA_ID, IDEA_VERSION),
    CONSTRAINT PK_PORTFOLIO_CANDIDATE PRIMARY KEY (ID)
);

CREATE INDEX IX_PORT_STATUS ON EIMS_PORTFOLIO_CANDIDATE (ELIGIBILITY_RESULT, PRIORITY);

CREATE TABLE EIMS_PORTFOLIO_MEMBERSHIP (
    ID                       VARCHAR2(64 CHAR) NOT NULL,
    PORTFOLIO_ID             VARCHAR2(64 CHAR) NOT NULL,
    CATALOG_ID               VARCHAR2(64 CHAR) NOT NULL,
    STATUS                   VARCHAR2(16 CHAR) NOT NULL,
    ASSIGNED_ROLE            VARCHAR2(64 CHAR),
    ASSIGNED_BY_ROLE         VARCHAR2(64 CHAR),
    ASSIGNED_AT              TIMESTAMP(6) WITH TIME ZONE,
    DECISION_REASON          VARCHAR2(2000 CHAR),
    ENTITY_VERSION                  NUMBER(10) DEFAULT 1 NOT NULL,
    CREATED_AT               TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT               TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_PORT_MEMBER_PORT FOREIGN KEY (PORTFOLIO_ID) REFERENCES EIMS_PORTFOLIO_CANDIDATE(ID),
    CONSTRAINT CK_PORT_MEMBER_STATUS CHECK (STATUS IN ('PROPOSED','ACCEPTED','REJECTED','DEFERRED')),
    CONSTRAINT CK_PORT_MEMBER_VERSION CHECK (ENTITY_VERSION >= 1),
    CONSTRAINT UQ_PORT_MEMBER_CATALOG UNIQUE (PORTFOLIO_ID, CATALOG_ID),
    CONSTRAINT UQ_PORT_MEMBER_ID_PORT UNIQUE (ID, PORTFOLIO_ID),
    CONSTRAINT PK_PORTFOLIO_MEMBERSHIP PRIMARY KEY (ID)
);

CREATE INDEX IX_PORT_MEMBER_STATUS ON EIMS_PORTFOLIO_MEMBERSHIP (STATUS, PORTFOLIO_ID);

CREATE TABLE EIMS_EXECUTION_RECOMMENDATION (
    ID                       VARCHAR2(64 CHAR) NOT NULL,
    MEMBERSHIP_ID            VARCHAR2(64 CHAR) NOT NULL,
    PORTFOLIO_ID             VARCHAR2(64 CHAR) NOT NULL,
    APPROVED_IDEA_VERSION_REF VARCHAR2(128 CHAR) NOT NULL,
    STATUS                   VARCHAR2(16 CHAR) NOT NULL,
    EXECUTION_DECISION       CLOB,
    GOVERNANCE_DECISION_REF VARCHAR2(128 CHAR),
    BASELINE_APPROVED       NUMBER(1) DEFAULT 0 NOT NULL,
    PORTFOLIO_BASELINE      CLOB,
    APPROVED_BASELINE_REF   VARCHAR2(128 CHAR),
    HANDOFF_STATE            VARCHAR2(16 CHAR) DEFAULT 'NOT_REQUESTED' NOT NULL,
    RECEIVING_EXECUTION_ID  VARCHAR2(64 CHAR),
    REQUESTED_BY_ROLE       VARCHAR2(64 CHAR),
    HANDOFF_REQUESTED_AT    TIMESTAMP(6) WITH TIME ZONE,
    ENTITY_VERSION                  NUMBER(10) DEFAULT 1 NOT NULL,
    THREAD_ID                VARCHAR2(128 CHAR),
    CREATED_AT               TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT               TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_EXEC_REC_MEMBER FOREIGN KEY (MEMBERSHIP_ID) REFERENCES EIMS_PORTFOLIO_MEMBERSHIP(ID),
    CONSTRAINT FK_EXEC_REC_PORT FOREIGN KEY (PORTFOLIO_ID) REFERENCES EIMS_PORTFOLIO_CANDIDATE(ID),
    CONSTRAINT FK_EXEC_REC_MEMBER_PORT FOREIGN KEY (MEMBERSHIP_ID, PORTFOLIO_ID) REFERENCES EIMS_PORTFOLIO_MEMBERSHIP(ID, PORTFOLIO_ID),
    CONSTRAINT CK_EXEC_REC_STATUS CHECK (STATUS IN ('DRAFT','SUBMITTED','APPROVED','REJECTED','RETURNED')),
    CONSTRAINT CK_EXEC_REC_BASELINE CHECK (BASELINE_APPROVED IN (0,1)),
    CONSTRAINT CK_EXEC_REC_HANDOFF CHECK (HANDOFF_STATE IN ('NOT_REQUESTED','REQUESTED','ACKNOWLEDGED')),
    CONSTRAINT CK_EXEC_REC_VERSION CHECK (ENTITY_VERSION >= 1),
    CONSTRAINT CK_EXEC_REC_DECISION_JSON CHECK (EXECUTION_DECISION IS NULL OR EXECUTION_DECISION IS JSON),
    CONSTRAINT CK_EXEC_REC_BASELINE_JSON CHECK (PORTFOLIO_BASELINE IS NULL OR PORTFOLIO_BASELINE IS JSON),
    CONSTRAINT UQ_EXEC_REC_MEMBER UNIQUE (MEMBERSHIP_ID),
    CONSTRAINT UQ_EXEC_REC_ID_PORT UNIQUE (ID, PORTFOLIO_ID),
    CONSTRAINT PK_EXECUTION_RECOMMENDATION PRIMARY KEY (ID)
);

CREATE INDEX IX_EXEC_REC_STATUS ON EIMS_EXECUTION_RECOMMENDATION (STATUS, HANDOFF_STATE);

CREATE TABLE EIMS_EXECUTION (
    ID                       VARCHAR2(64 CHAR) NOT NULL,
    RECOMMENDATION_ID        VARCHAR2(64 CHAR) NOT NULL,
    PORTFOLIO_ID             VARCHAR2(64 CHAR) NOT NULL,
    IDEA_ID                  VARCHAR2(64 CHAR) NOT NULL,
    TITLE                    VARCHAR2(1000 CHAR) NOT NULL,
    OWNER_ID                 VARCHAR2(128 CHAR),
    OWNER_ROLE               VARCHAR2(64 CHAR) DEFAULT 'EXECUTION_OWNER' NOT NULL,
    PROGRESS_PERCENT         NUMBER(5,2) DEFAULT 0 NOT NULL,
    RISK_LEVEL               VARCHAR2(16 CHAR) DEFAULT 'MEDIUM' NOT NULL,
    STATUS                   VARCHAR2(24 CHAR) DEFAULT 'PLANNING' NOT NULL,
    CHARTER_APPROVED         NUMBER(1) DEFAULT 0 NOT NULL,
    PLAN_APPROVED            NUMBER(1) DEFAULT 0 NOT NULL,
    BENEFIT_STATUS           VARCHAR2(32 CHAR) DEFAULT 'NOT_STARTED' NOT NULL,
    HANDOFF_ACCEPTED_AT      TIMESTAMP(6) WITH TIME ZONE,
    ENTITY_VERSION                  NUMBER(10) DEFAULT 1 NOT NULL,
    THREAD_ID                VARCHAR2(128 CHAR),
    CREATED_AT               TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT               TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_EXEC_RECOMMENDATION FOREIGN KEY (RECOMMENDATION_ID) REFERENCES EIMS_EXECUTION_RECOMMENDATION(ID),
    CONSTRAINT FK_EXEC_PORT FOREIGN KEY (PORTFOLIO_ID) REFERENCES EIMS_PORTFOLIO_CANDIDATE(ID),
    CONSTRAINT FK_EXEC_REC_PORT_MATCH FOREIGN KEY (RECOMMENDATION_ID, PORTFOLIO_ID) REFERENCES EIMS_EXECUTION_RECOMMENDATION(ID, PORTFOLIO_ID),
    CONSTRAINT CK_EXEC_PROGRESS CHECK (PROGRESS_PERCENT BETWEEN 0 AND 100),
    CONSTRAINT CK_EXEC_RISK CHECK (RISK_LEVEL IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    CONSTRAINT CK_EXEC_STATUS CHECK (STATUS IN ('PLANNING','ACTIVE','ON_HOLD','COMPLETED','CANCELLED')),
    CONSTRAINT CK_EXEC_FLAGS CHECK (CHARTER_APPROVED IN (0,1) AND PLAN_APPROVED IN (0,1)),
    CONSTRAINT CK_EXEC_BENEFIT_STATUS CHECK (BENEFIT_STATUS IN ('NOT_STARTED','IN_PROGRESS','REALIZED','CLOSED')),
    CONSTRAINT CK_EXEC_VERSION CHECK (ENTITY_VERSION >= 1),
    CONSTRAINT UQ_EXEC_RECOMMENDATION UNIQUE (RECOMMENDATION_ID),
    CONSTRAINT UQ_EXEC_ID_PORT UNIQUE (ID, PORTFOLIO_ID),
    CONSTRAINT PK_EXECUTION PRIMARY KEY (ID)
);

CREATE INDEX IX_EXEC_STATUS ON EIMS_EXECUTION (STATUS, OWNER_ROLE);

CREATE TABLE EIMS_BENEFIT (
    ID                       VARCHAR2(64 CHAR) NOT NULL,
    EXECUTION_ID             VARCHAR2(64 CHAR) NOT NULL,
    IDEA_ID                  VARCHAR2(64 CHAR) NOT NULL,
    TITLE                    VARCHAR2(1000 CHAR) NOT NULL,
    STATUS                   VARCHAR2(40 CHAR) DEFAULT 'OBLIGATION_PENDING_ACCEPTANCE' NOT NULL,
    OWNER_ID                 VARCHAR2(128 CHAR),
    ACCEPTANCE_DOSSIER       CLOB,
    BASELINE_DOSSIER         CLOB,
    MEASUREMENT_PLAN         CLOB,
    MEASUREMENT_DOSSIER      CLOB,
    VERIFICATION_DOSSIER     CLOB,
    ATTRIBUTION_DOSSIER      CLOB,
    REALIZATION_DOSSIER      CLOB,
    CONFIDENCE               VARCHAR2(32 CHAR),
    VERIFIED_KPI             VARCHAR2(256 CHAR),
    ENTITY_VERSION                  NUMBER(10) DEFAULT 1 NOT NULL,
    THREAD_ID                VARCHAR2(128 CHAR),
    CREATED_AT               TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT               TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_BEN_EXECUTION FOREIGN KEY (EXECUTION_ID) REFERENCES EIMS_EXECUTION(ID),
    CONSTRAINT CK_BEN_STATUS CHECK (STATUS IN (
        'OBLIGATION_PENDING_ACCEPTANCE','BASELINE_REQUIRED','PLAN_REQUIRED',
        'MEASUREMENT_PENDING','MEASURED','VERIFIED','VALIDATED','REALIZED','CLOSED')),
    CONSTRAINT CK_BEN_CONFIDENCE CHECK (CONFIDENCE IS NULL OR CONFIDENCE IN ('UNVERIFIED','VERIFIED')),
    CONSTRAINT CK_BEN_VERSION CHECK (ENTITY_VERSION >= 1),
    CONSTRAINT CK_BEN_ACCEPT_JSON CHECK (ACCEPTANCE_DOSSIER IS NULL OR ACCEPTANCE_DOSSIER IS JSON),
    CONSTRAINT CK_BEN_BASE_JSON CHECK (BASELINE_DOSSIER IS NULL OR BASELINE_DOSSIER IS JSON),
    CONSTRAINT CK_BEN_PLAN_JSON CHECK (MEASUREMENT_PLAN IS NULL OR MEASUREMENT_PLAN IS JSON),
    CONSTRAINT CK_BEN_MEASURE_JSON CHECK (MEASUREMENT_DOSSIER IS NULL OR MEASUREMENT_DOSSIER IS JSON),
    CONSTRAINT CK_BEN_VERIFY_JSON CHECK (VERIFICATION_DOSSIER IS NULL OR VERIFICATION_DOSSIER IS JSON),
    CONSTRAINT CK_BEN_ATTR_JSON CHECK (ATTRIBUTION_DOSSIER IS NULL OR ATTRIBUTION_DOSSIER IS JSON),
    CONSTRAINT CK_BEN_REALIZE_JSON CHECK (REALIZATION_DOSSIER IS NULL OR REALIZATION_DOSSIER IS JSON),
    CONSTRAINT UQ_BEN_EXECUTION UNIQUE (EXECUTION_ID),
    CONSTRAINT PK_BENEFIT PRIMARY KEY (ID)
);

CREATE INDEX IX_BEN_STATUS ON EIMS_BENEFIT (STATUS);

CREATE TABLE EIMS_KNOWLEDGE_ASSET (
    ID                       VARCHAR2(64 CHAR) NOT NULL,
    BENEFIT_ID               VARCHAR2(64 CHAR) NOT NULL,
    TITLE                    VARCHAR2(1000 CHAR) NOT NULL,
    STATUS                   VARCHAR2(16 CHAR) DEFAULT 'DRAFT' NOT NULL,
    AUTHOR_ROLE              VARCHAR2(64 CHAR),
    AUTHOR_COMPLETED         NUMBER(1) DEFAULT 0 NOT NULL,
    CONTENT                  CLOB,
    CAPTURE_DOSSIER          CLOB,
    VALIDATION_DOSSIER       CLOB,
    PUBLICATION_DOSSIER      CLOB,
    PUBLICATION_VERSION      VARCHAR2(32 CHAR),
    PUBLICATION_REF          VARCHAR2(128 CHAR),
    PUBLISHED_AT             TIMESTAMP(6) WITH TIME ZONE,
    ENTITY_VERSION                  NUMBER(10) DEFAULT 1 NOT NULL,
    CREATED_AT               TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT               TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_KNOW_BENEFIT FOREIGN KEY (BENEFIT_ID) REFERENCES EIMS_BENEFIT(ID),
    CONSTRAINT CK_KNOW_STATUS CHECK (STATUS IN ('DRAFT','CONDITIONAL','VALIDATED','PUBLISHED','REJECTED')),
    CONSTRAINT CK_KNOW_AUTHOR_COMPLETED CHECK (AUTHOR_COMPLETED IN (0,1)),
    CONSTRAINT CK_KNOW_VERSION CHECK (ENTITY_VERSION >= 1),
    CONSTRAINT UQ_KNOW_BENEFIT UNIQUE (BENEFIT_ID),
    CONSTRAINT CK_KNOW_CAPTURE_JSON CHECK (CAPTURE_DOSSIER IS NULL OR CAPTURE_DOSSIER IS JSON),
    CONSTRAINT CK_KNOW_VALIDATION_JSON CHECK (VALIDATION_DOSSIER IS NULL OR VALIDATION_DOSSIER IS JSON),
    CONSTRAINT CK_KNOW_PUBLICATION_JSON CHECK (PUBLICATION_DOSSIER IS NULL OR PUBLICATION_DOSSIER IS JSON),
    CONSTRAINT PK_KNOWLEDGE_ASSET PRIMARY KEY (ID)
);

CREATE INDEX IX_KNOW_STATUS ON EIMS_KNOWLEDGE_ASSET (STATUS);

GRANT SELECT, INSERT, UPDATE ON EIMS_PORTFOLIO_CANDIDATE TO EIMS_APP;
GRANT SELECT, INSERT, UPDATE ON EIMS_PORTFOLIO_MEMBERSHIP TO EIMS_APP;
GRANT SELECT, INSERT, UPDATE ON EIMS_EXECUTION_RECOMMENDATION TO EIMS_APP;
GRANT SELECT, INSERT, UPDATE ON EIMS_EXECUTION TO EIMS_APP;
GRANT SELECT, INSERT, UPDATE ON EIMS_BENEFIT TO EIMS_APP;
GRANT SELECT, INSERT, UPDATE ON EIMS_KNOWLEDGE_ASSET TO EIMS_APP;

COMMIT;
